[package]
name = "dendrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
nannou_audio = "0.19.0"
audrey = "0.3"
chrono = "0.4.35"